In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv


SyntaxError: invalid syntax (3145835708.py, line 1)

# Module 1 

## Question 1. Pandas version

In [4]:
import pandas as pd

In [5]:
pd.__version__

'2.2.2'

##  Question 2. Records count

In [6]:
ds = pd.read_csv('laptops.txt')

In [7]:
ds.shape

(2160, 12)

## Question 3. Laptop brands 


In [8]:
ds.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [11]:
brands = ds['Brand'].unique()

In [12]:
type(brands)

numpy.ndarray

In [14]:
brands

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [13]:
brands.size

27

## Question 4. Missing values 

In [17]:
ds.isnull().values.any()


True

In [18]:
 ds.columns[ds.isna().any()].tolist()

['Storage type', 'GPU', 'Screen']

In [19]:
ds.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [20]:
ds.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [21]:
ds.isnull().any()

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool

## Question 5. Maximum final price 

In [23]:
ds_Dell = ds[ds['Brand']=='Dell'] 


In [25]:
ds_Dell.shape

(84, 12)

In [26]:
ds_Dell.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [28]:
ds_Dell['Final Price'].max()

3936.0

## Question 6. Median value of Screen

In [30]:
ds.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [33]:
ds['Screen'].median()

15.6

### most frquent value

In [34]:
ds['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [35]:
df=ds

In [40]:
df["Screen"].fillna( 15.6, inplace = True)


In [41]:
 df.columns[df.isna().any()].tolist()

['Storage type', 'GPU']

In [42]:
df['Screen'].median()

15.6

## Question 7. Sum of weights

In [ ]:
 = ds[ds['']]

In [43]:
df_Innjoo = ds[ds['Brand']=='Innjoo'] 


In [44]:
df_Innjoo.shape

(6, 12)

In [45]:
df_Innjoo.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [50]:
df_Innjoo2 = df_Innjoo[df_Innjoo['RAM', 'Storage', 'Screen']]

KeyError: ('RAM', 'Storage', 'Screen')

In [51]:
df_Innjoo_2 = df_Innjoo.filter(['RAM', 'Storage', 'Screen'], axis=1)


In [52]:
df_Innjoo_2.shape

(6, 3)

In [53]:
X = df_Innjoo_2.to_numpy()


In [54]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [56]:
XT = X.transpose()

In [57]:
XT

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [66]:
XTX = np.matmul(XT, X)

In [67]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [68]:
XTX.shape

(3, 3)

In [61]:
import numpy as np
from numpy.linalg import inv
#https://www.tutorialspoint.com/compute-the-multiplicative-inverse-of-a-matrix-in-python#:~:text=To%20compute%20the%20(multiplicative)%20inverse,a)%20%3D%20eye(a.

In [69]:
inv_XTX = np.linalg.inv(XTX)


array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

### create array 

In [70]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [71]:
inv_XTX = np.linalg.inv(XTX)


In [72]:
inv_XTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

#### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.


In [73]:
invxtx_xt_mul = np.matmul(inv_XTX, XT)

In [74]:
invxtx_xt_mul

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [75]:
w = np.matmul(invxtx_xt_mul, y)

In [76]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [77]:
np.sum(w)

91.29988062995815